.vscode/launch.json
package.json
src/db-mgmt/reset.ts
src/models/entities/Agreement.ts
src/models/entities/Challenge.ts
src/models/entities/Context.ts
src/models/entities/DID.ts
src/models/entities/Ecoverse.ts
src/models/entities/Organisation.ts
src/models/entities/Project.ts
src/models/entities/Tag.ts
src/models/entities/User.ts
src/models/entities/UserGroup.ts
src/models/inputs/EcoverseInput.ts
src/schema/Resolvers.ts
src/server.ts
src/test/db_reset.ts

Server#16 - refactored api

---

package.json

Corrects the server version number

Version number to indicate in development mode - closes #24

---

package-lock.json
package.json

Added nodemon to the project and 'start' script was updated to use the nodemon.
Allows reloading of the project on file changes

Added nodemon to the project

---

README.md
src/connection-factory.ts
src/db-mgmt/reset.ts
src/server.ts

Creates connection factory that build the connection for the typeorm.

Fix connection creation

---

src/models/entities/Ecoverse.ts
src/schema/Resolvers.ts

Applied Singleton pattern to Ecoverse - Resolves Server #38

---

src/db-mgmt/challenge.ts
src/db-mgmt/reset.ts
src/models/entities/Context.ts
src/models/inputs/ContextInput.ts

Extends Context with additional fields to capture the elements of a challenge.
Extended the columns sizes for context
Extended sample script to have a chalelnge with additional text in there.

Extend challenge information - closes Server#27

---

.github/workflows/docker-image.yml

Updated CI to trigger off the develop branch

Updated CI to trigger off the develop branch

---

src/models/entities/Challenge.ts
src/models/entities/Ecoverse.ts
src/models/entities/Reference.ts
src/schema/inputs/ChallengeInput.ts
src/schema/inputs/EcoverseInput.ts

updated the size limits to be able to upload Odyssey challenges on the challenge/ecoverse name + reference description
To test: upload the sample challenges from odysseymomentumexperience/ecoverse/sampledata/challenges folder + using the demo repo.

updated the size limits  - closes server#75

---

manifests/25-server-deployment.yaml

Updated the deployment to only have 1 pod

---

src/server.ts

Added flag for enabling authentication

---

.eslintrc.json
src/db-mgmt/reset.ts
src/security/authentication/bearerStrategy.ts
src/server.ts

- Configure CORS 
- fix some deprecation messages according the express-session
- remove excessive console.logs
- Authentication is enabled by default

Configure Apollo Server CORS middleware for CT Server 

---

src/server.ts

Fix authentication enable/disable

Fix authentication enable/disable

---

README.md

Updated README.MD with AAD authentication environment variables. Resolves server#95

---

README.md
src/security/authentication/aad-connection-factory.ts
src/security/authentication/config.ts

Updated token / endpoint configuration to AAD v2.0 - resolves server#100

---

src/security/authentication/index.ts

Fixed bug. Resolves Server #108

---

README.md

Updatet README.MD with CORS configuration. Closes Server #114

---

README.md

adding the BCH badge
shows build quality

Adding the BetterCodeHub Badge

---

package.json
src/interfaces/IReference.ts
src/models/entities/Reference.ts
src/schema/inputs/ReferenceInput.ts
src/schema/inputs/UserInput.ts
src/schema/resolvers/CreateMutations.ts
src/schema/resolvers/Queries.ts
src/schema/resolvers/UpdateMutations.ts
src/services/UserService.ts

Modified createUser to check for unique email address if one if given
made description on reference optional
added additional fields to UserInput type
increase package.json number to 0.1.8

Series of api updates to allow loading of sample user data + version update to v0.1.8 

---

src/domain/challenge/challenge.resolver.ts
src/domain/challenge/challenge.service.ts
src/domain/ecoverse/ecoverse.module.ts
src/domain/ecoverse/ecoverse.resolver.ts
src/domain/ecoverse/ecoverse.service.ts
src/domain/organisation/organisation.resolver.ts
src/domain/organisation/organisation.service.ts
src/domain/profile/profile.resolver.ts
src/domain/profile/profile.service.ts
src/domain/tagset/tagset.resolver.ts
src/domain/tagset/tagset.service.ts
src/domain/user-group/user-group.module.ts

new mutation: createTagsetOnProfile
new mutation: replaceTagsOnTagset
Fixed error in logic of tagsetService.createRestrictedTagset
Note: this branches from previous PRs - need to chat about how best to do these kind of incremental PRs.

replaces PR#174 - add tagset related mutations - closes Server169

---

src/domain/challenge/challenge.resolver.ts
src/domain/challenge/challenge.service.ts
src/domain/ecoverse/ecoverse.module.ts
src/domain/ecoverse/ecoverse.resolver.ts
src/domain/ecoverse/ecoverse.service.ts
src/domain/organisation/organisation.resolver.ts
src/domain/organisation/organisation.service.ts
src/domain/user-group/user-group.module.ts

Migrated the folllowing mutations:
- createGroupOnOrganisation
- createGroupOnChallenge

mutations for creating groups to orgs + challenges - closes Server-168

---

src/domain/ecoverse/ecoverse.module.ts
src/domain/ecoverse/ecoverse.resolver.mutations.ts
src/domain/ecoverse/ecoverse.resolver.queries.ts
src/domain/ecoverse/ecoverse.resolver.ts
src/domain/ecoverse/ecoverse.service.ts
src/domain/user-group/user-group.module.ts

Migrates the addGroupOnEcoverse mutation to v0.2

Muation: addGroupOnEcoverse - closes Server-166

---

src/domain/ecoverse/ecoverse.resolver.mutations.ts
src/domain/user/user.dto.ts

fixed bug that had the wrong name in teh mutation on ecoverse for creating group

---

src/domain/challenge/challenge.module.ts
src/domain/context/context.module.ts
src/domain/ecoverse/ecoverse.module.ts
src/domain/organisation/organisation.module.ts
src/domain/profile/profile.module.ts
src/domain/reference/reference.module.ts
src/domain/user-group/user-group.module.ts
src/domain/user/user.module.ts

Fixed module dependencies. Closes #183.

---

src/domain/ecoverse/ecoverse.module.ts
src/domain/ecoverse/ecoverse.resolver.mutations.ts
src/domain/ecoverse/ecoverse.service.ts
src/domain/user/user.dto.ts
src/domain/user/user.service.ts
src/utils/data-management/data-management.module.ts

added mutation for creating user; 
user automatically gets added to members group; 
fixed module proviers in datamgmt module
New branch due to merge without signed commit on previous branches

added mutation for creating user; user automatically gets added to members group; fixed module proviers in datamgmt module

---

graphql-samples/mutations/update/update-challenge
src/domain/challenge/challenge.module.ts
src/domain/challenge/challenge.resolver.ts
src/domain/challenge/challenge.service.ts
src/domain/ecoverse/ecoverse.service.ts
src/utils/data-management/data-management.module.ts

adds in updateChallenge mutation - closes Server 194

---

graphql-samples/mutations/create/create-challenge
graphql-samples/mutations/create/create-group-on-challenge
graphql-samples/mutations/create/create-organisation
graphql-samples/mutations/create/create-user
graphql-samples/mutations/create/create-userGroup
graphql-samples/mutations/update/add-user-to-group
graphql-samples/mutations/update/replace-tags-on-tagset
graphql-samples/mutations/update/update-organisation
src/domain/challenge/challenge.resolver.ts
src/domain/ecoverse/ecoverse.entity.ts
src/domain/ecoverse/ecoverse.interface.ts
src/domain/ecoverse/ecoverse.module.ts
src/domain/ecoverse/ecoverse.resolver.mutations.ts
src/domain/ecoverse/ecoverse.service.ts
src/domain/organisation/organisation.entity.ts
src/domain/organisation/organisation.module.ts
src/domain/organisation/organisation.service.ts
src/domain/user-group/user-group.resolver.ts

The creation of the org is throwing an error - would like to have that as a separate issue on the board if you are ok with the code setup.
Closes: 192 & 200

Adds in createOrganisation mutation; adds in mutation samples

---

graphql-samples/mutations/update/update-organisation
src/domain/context/context.module.ts
src/domain/context/context.service.ts
src/domain/ecoverse/ecoverse.service.ts
src/domain/reference/reference.service.ts
src/domain/user/user.service.ts

Fixed various bugs to be able to get the structure + user loading working.
To validate use the odyssey structure + user loading

Updates to get the ecoverse structure + user loading working

---

src/domain/ecoverse/ecoverse.entity.ts
src/domain/ecoverse/ecoverse.interface.ts
src/domain/ecoverse/ecoverse.resolver.queries.ts
src/domain/ecoverse/ecoverse.service.ts
src/domain/organisation/organisation.service.ts
src/main.ts
src/utils/bootstrap/bootstrap.module.ts
src/utils/bootstrap/bootstrap.service.ts
src/utils/data-management/data-management.module.ts
src/utils/data-management/data-management.service.ts

Unfortunately a bigger PR - as had to sort out the bootstrapping to get the organisations working (related to host org + how that was being setup)

Simplify bootstrapping process; new queries for organisations

---

graphql-samples/mutations/update/update-user
src/domain/user/user.resolver.ts
src/domain/user/user.service.ts

Added mutation and sample file for updating a user

Added mutation and sample file for updating a user

---

src/utils/data-management/data-management.controller.ts
src/utils/data-management/data-management.service.ts

Creates a simple html page at the data-management location that can be used to trigger the data management actions supported by the server

added in a simple page for triggering the various data mgmt actions

---

README.md

updated documentation related to populating the sample data in the server

---

graphql-samples/mutations/update/add-user-to-challenge
src/domain/challenge/challenge.module.ts
src/domain/challenge/challenge.resolver.ts
src/domain/challenge/challenge.service.ts
src/domain/user-group/user-group.service.ts

One of the key logical actions is to add a user to a challenge i.e. to add the user to the members group for a challenge
New mutation is there
New sample file created

new mutation to add a user to a challenge

---

src/domain/user-group/user-group.entity.ts

Fix user group to organisation relation

---

src/domain/user/user.decorator.ts
src/domain/user/user.resolver.ts

Added me query returning the currently logged in user.
To test it log in with the client and add the Bearer token as authorization header in the HTTP headers in GQL playground.

Added 'me' query returning the currently logged in user. Closes #216.

---

graphql-samples/mutations/update/add-tag-to-tagset
graphql-samples/mutations/update/replace-tags-on-tagset
package.json
src/domain/tagset/tagset.module.ts
src/domain/tagset/tagset.resolver.ts
src/domain/tagset/tagset.service.ts
src/domain/user-group/user-group.entity.ts
src/domain/user-group/user-group.interface.ts

updated version number to 0.2.2; 
fixed profile to be always present on usergroup; 
added sample file for mutation and fixed a typo in another mutation sample file

new mutation to add a tag to a tagset; misc minor updates

---

src/domain/tagset/tagset.service.ts
src/domain/user-group/user-group.service.ts

Also made update from previous PR about doing array member checking via includes()

Fixed issue whereby groups were not being initialised after being created

---

.vscode/launch.json
package-lock.json

Update launch configuration to use the nest CLI instead of ts-node. Also it adds `--watch` switch for better development experience.

Update launch configuration

---

src/interfaces/service.config.interface.ts
src/utils/authentication/aad.strategy.ts
src/utils/authentication/graphql.guard.ts
src/utils/config/service.config.ts

Re-integrate AUTHENTICATION_ENABLED flag. Closes #255.

---

src/domain/challenge/challenge.service.ts
src/domain/ecoverse/ecoverse.entity.ts
src/domain/ecoverse/ecoverse.service.ts
src/domain/organisation/organisation.service.ts
src/domain/tagset/tagset.service.ts
src/domain/user-group/user-group.entity.ts
src/domain/user-group/user-group.interface.ts
src/domain/user-group/user-group.service.ts
src/utils/data-management/data-management.service.ts

API Optimisations (Act 2)

---

src/domain/challenge/challenge.service.ts
src/domain/ecoverse/ecoverse.service.ts
src/domain/profile/profile.service.ts
src/domain/tagset/tagset.service.ts
src/domain/user-group/user-group.service.ts
src/utils/data-management/data-management.module.ts
src/utils/data-management/data-management.service.ts

,not direct calls; 
fixed a couple of async calls not being waited

updated sample data loading to go through service methods

---

src/domain/ecoverse/ecoverse.service.ts
src/domain/user-group/user-group.service.ts
src/utils/data-management/data-management.service.ts

Fix ecoverse members loading

---

README.md
src/domain/ecoverse/ecoverse.entity.ts
src/domain/ecoverse/ecoverse.service.ts
src/domain/user-group/user-group.entity.ts
src/domain/user-group/user-group.service.ts
src/domain/user/user.service.ts
src/interfaces/bootstrap.interface.ts
src/interfaces/service.config.interface.ts
src/utils/bootstrap/bootstrap.service.ts
src/utils/config/authorisation-bootstrap.json
src/utils/config/service.config.ts

Bootstrap of CT roles. Currently the user groups are only 'appended' to the user - there is no logic to replace / remove roles (straightforward fix if required).
Read the README to understand how to use it.

Bootstrapping CT roles. Closes Server#240.

---

.vscode/settings.json
src/domain/challenge/challenge.entity.ts
src/domain/challenge/challenge.interface.ts
src/domain/challenge/challenge.service.ts
src/domain/ecoverse/ecoverse.entity.ts
src/domain/ecoverse/ecoverse.interface.ts
src/domain/ecoverse/ecoverse.service.ts
src/domain/organisation/organisation.entity.ts
src/domain/organisation/organisation.interface.ts
src/domain/organisation/organisation.service.ts
src/domain/project/project.entity.ts
src/domain/project/project.interface.ts
src/domain/tagset/tagset.entity.ts
src/domain/tagset/tagset.service.ts
src/utils/bootstrap/bootstrap.service.ts
src/utils/data-management/data-management.service.ts

Fix tagset and context initiliazation

---

src/domain/ecoverse/ecoverse.service.ts

Clean up console timers.

---

src/domain/user-group/user-group.service.ts
src/utils/authentication/graphql.guard.ts

Improve authorization error messages - now the error correctly will tell why user can not be authorized.
Fix adding user into the DB - restrict adding users with the same e-mail instead of same name.

Ad hoc improvements

---

src/domain/user/user.module.ts
src/domain/user/user.resolver.ts
src/utils/authentication/aad.strategy.ts
src/utils/authentication/authentication.module.ts
src/utils/bootstrap/bootstrap.service.ts
src/utils/ms-graph/ms-graph.module.ts
src/utils/ms-graph/ms-graph.service.ts

Added profile and account creation mutations. Fixed a bootstrap bug. Closes #297.

---

src/domain/challenge/challenge.interface.ts
src/domain/user/user.service.ts

checks that a valid email address is provided

updated checking on user creation

---

graphql-samples/mutations/create/create-challenge
graphql-samples/mutations/create/create-opportunity-on-challenge
graphql-samples/mutations/update/update-opportunity
src/domain/challenge/challenge.entity.ts
src/domain/challenge/challenge.interface.ts
src/domain/challenge/challenge.module.ts
src/domain/challenge/challenge.resolver.ts
src/domain/challenge/challenge.service.ts
src/domain/context/context.dto.ts
src/domain/opportunity/opportunity.dto.ts
src/domain/opportunity/opportunity.entity.ts
src/domain/opportunity/opportunity.interface.ts
src/domain/opportunity/opportunity.module.ts
src/domain/opportunity/opportunity.resolver.spec.ts
src/domain/opportunity/opportunity.resolver.ts
src/domain/opportunity/opportunity.service.spec.ts
src/domain/opportunity/opportunity.service.ts
src/domain/project/project.entity.ts
src/domain/project/project.interface.ts

Also moved Projects to be under Opportunity; 
renamed lifecyclePhase to be state at all levels (Challenge, Opportunity, Project) & updates sample files
Added graphql sample files

Added in Opportunity entity, 

---

src/domain/ecoverse/ecoverse.service.ts
src/domain/user-group/user-group.entity.ts
src/domain/user-group/user-group.resolver.ts
src/domain/user-group/user-group.service.ts
src/domain/user/user.dto.ts
src/domain/user/user.entity.ts
src/domain/user/user.interface.ts
src/domain/user/user.service.ts
src/interfaces/groupable.interface.ts
src/utils/authentication/aad.strategy.ts
src/utils/authentication/graphql.guard.ts
src/utils/bootstrap/bootstrap.service.ts

Removed eager / lazy loading. Loading entities on demand. AddUserToGroup is refactored to use raw sql.

Server 298. Closes #298

---

src/utils/ms-graph/ms-graph.service.ts

Fixed user account creation bug. Closes #316.

---

src/utils/ms-graph/ms-graph.service.ts

Updated AAD user information - added givenName + surname. Closes #310.

---

src/domain/ecoverse/ecoverse.resolver.mutations.ts
src/domain/ecoverse/ecoverse.service.ts
src/domain/user/user.module.ts
src/domain/user/user.resolver.ts
src/domain/user/user.service.ts
src/utils/account/account.module.ts
src/utils/account/account.resolver.ts
src/utils/account/account.service.ts
src/utils/bootstrap/bootstrap.service.ts
src/utils/data-management/data-management.service.ts

Moved the createUserAccount and createUserProfile to be on ecoverse
updated createUserProfile to also add the user to the members group
Removed MSGraph dependency from User module
Tidied up methods on bootstrap to remove flags / parameters not needed and to only call createUserProfile

fixed boostrapping of profiles; moved creating of users to ecoverse fully

---

graphql-samples/mutations/update/update-avatar-on-profile
src/domain/profile/profile.entity.ts
src/domain/profile/profile.interface.ts
src/domain/profile/profile.resolver.ts
src/domain/profile/profile.service.ts

new avatar field on profile which is a uri
added sample graphql file

added avatar field on Profile

---

README.md
package-lock.json
package.json
src/app.module.ts
src/domain/challenge/challenge.service.ts
src/domain/ecoverse/ecoverse.service.ts
src/domain/organisation/organisation.service.ts
src/domain/tagset/tagset.service.ts
src/domain/user-group/user-group.service.ts
src/domain/user/user.service.ts
src/interfaces/aad.config.interface.ts
src/main.ts
src/utils/authentication/aad.strategy.ts
src/utils/authentication/graphql.guard.ts
src/utils/bootstrap/bootstrap.service.ts
src/utils/config/aad.config.ts
src/utils/config/winston.config.ts
src/utils/data-management/data-management.service.ts
src/utils/ms-graph/ms-graph.service.ts

Server 89. Closes #89.

---

README.md
package.json
src/domain/ecoverse/ecoverse.service.ts
src/domain/user/user.dto.ts
src/domain/user/user.entity.ts
src/domain/user/user.interface.ts
src/domain/user/user.service.ts
src/interfaces/aad.config.interface.ts
src/utils/account/account.resolver.ts
src/utils/account/account.service.ts
src/utils/bootstrap/bootstrap.service.ts
src/utils/config/aad.config.ts
src/utils/ms-graph/ms-graph.service.ts

adds accountUpn field to the User entity
update the account creation logic to generate a UPN based on firstname.lastname@upn_domain
added an enviornment variable that specifies the upndomain to be used
updated readme to detail the new environment variable
updated version number to 0.3.2

Added support for accountUpn that is independent of email

---

src/domain/user-group/user-group.service.ts

Server 319. Closes #319.

---

test/user/create-user.e2e-spec.ts
test/user/remove-user.e2e-spec.ts
test/user/update-user.e2e-spec.ts
test/user/user-to-group.e2e-spec.ts
test/user/user.request.params.ts

Refactored parameters to use one variable: uniqueId

Enabled test "Create same user twice";

---

test/user/user-to-group.e2e-spec.ts

Eabled "removeUserFromGroup"

---

package.json
src/domain/profile/profile.service.ts
src/domain/user/user.entity.ts
src/domain/user/user.interface.ts
src/domain/user/user.service.ts

Fixed a couple of missing awaits in Profile
Updated version number to 0.3.3

Added lastModified field to User

---

src/utils/data-management/data-management.service.ts

fixed sample data to supply mandatory user profile fields; updated data to be non-team member focused

---

graphql-samples/mutations/create/create-template
src/domain/ecoverse/ecoverse.entity.ts
src/domain/ecoverse/ecoverse.interface.ts
src/domain/ecoverse/ecoverse.module.ts
src/domain/ecoverse/ecoverse.resolver.mutations.ts
src/domain/ecoverse/ecoverse.resolver.queries.ts
src/domain/ecoverse/ecoverse.service.ts
src/domain/template/template.dto.ts
src/domain/template/template.entity.ts
src/domain/template/template.interface.ts
src/domain/template/template.module.ts
src/domain/template/template.resolver.spec.ts
src/domain/template/template.resolver.ts
src/domain/template/template.service.ts
src/domain/user/user.entity.ts

new entity: Template
new query: templates
new mutation: createTemplate
new sample file for creating a new template
The population of a template to be another issue.

Added support for templates, with each template for now only containing user definitions

---

graphql-samples/mutations/create/create-aspect
src/domain/aspect/aspect.dto.ts
src/domain/aspect/aspect.entity.ts
src/domain/aspect/aspect.interface.ts
src/domain/aspect/aspect.module.ts
src/domain/aspect/aspect.resolver.spec.ts
src/domain/aspect/aspect.resolver.ts
src/domain/aspect/aspect.service.ts
src/domain/opportunity/opportunity.entity.ts
src/domain/opportunity/opportunity.interface.ts
src/domain/opportunity/opportunity.module.ts
src/domain/opportunity/opportunity.resolver.ts
src/domain/opportunity/opportunity.service.ts

New entity: Aspect
Opportunity updated to have an array of aspects
new mutation for adding an aspect to an Opportunity

Added Aspect entity and usage of aspects by Opportunity

---

graphql-samples/mutations/create/create-actor
src/domain/actor-group/actor-group.dto.ts
src/domain/actor-group/actor-group.entity.ts
src/domain/actor-group/actor-group.interface.ts
src/domain/actor-group/actor-group.module.ts
src/domain/actor-group/actor-group.resolver.spec.ts
src/domain/actor-group/actor-group.resolver.ts
src/domain/actor-group/actor-group.service.ts
src/domain/actor/actor.dto.ts
src/domain/actor/actor.entity.ts
src/domain/actor/actor.interface.ts
src/domain/actor/actor.module.ts
src/domain/actor/actor.resolver.spec.ts
src/domain/actor/actor.resolver.ts
src/domain/actor/actor.service.ts
src/domain/opportunity/opportunity.entity.ts
src/domain/opportunity/opportunity.interface.ts
src/domain/opportunity/opportunity.module.ts
src/domain/opportunity/opportunity.service.ts
src/utils/data-management/data-management.service.ts

New entity: ActorGroup
New entity: Actor
New mutation: createActor, together with a sample mutation file
Challenge entity updated to hold a list of actor groups
Support for default actor groups on Challenge
Notes:
- tests still to be added, will need some pointers / help on that
- additional mutations will be in a separate issue

Added ActorGroup & Actor entities

---

package-lock.json
package.json
src/utils/account/account.service.ts
src/utils/bootstrap/bootstrap.service.ts

createUserAccount mutation bug fixed; ensure generated upn does not have spaces

---

test/performance/README.md
test/performance/performance-plan-ct.jmx
test/performance/results-2020-11-01.md

Performance tests and documentation

---

graphql-samples/mutations/update/update-avatar-on-profile
graphql-samples/mutations/update/update-profile
package.json
src/domain/profile/profile.dto.ts
src/domain/profile/profile.entity.ts
src/domain/profile/profile.interface.ts
src/domain/profile/profile.resolver.ts
src/domain/profile/profile.service.ts

added description field to avatar + reworked update method

---

.env.default
package-lock.json
src/domain/template/template.service.ts
src/interfaces/service.config.interface.ts
src/utils/bootstrap/bootstrap.module.ts
src/utils/bootstrap/bootstrap.service.ts
src/utils/config/service.config.ts
src/utils/config/templates-bootstrap.json

new bootstrap method to load in templates
templates default file in config
templates location controllable via environment variable

support the loading of template data as part of bootstrap

---

graphql-samples/mutations/create/create-group-on-challenge
src/domain/challenge/challenge.entity.ts
src/domain/challenge/challenge.resolver.fields.ts
src/domain/challenge/challenge.service.ts

To start dealing with the findings of the load testing results from Evgeni.

removed eager loading on groups from challenges

---

graphql-samples/mutations/update/update-actor
graphql-samples/remove/remove-actor
src/domain/actor/actor.dto.ts
src/domain/actor/actor.resolver.ts
src/domain/actor/actor.service.ts

added mutations for updating and removing actors

---

src/domain/actor/actor.service.ts
src/domain/reference/reference.dto.ts
src/domain/reference/reference.entity.ts

allow the description field on reference to be optional

---

test/challenge/challenge-test-scenarios.md
test/challenge/challenge.request.params.ts
test/challenge/create-challenge.e2e-spec.ts
test/group/group.request.params.ts

Added "Create Challenge" tests

---

src/domain/challenge/challenge.entity.ts
src/domain/challenge/challenge.resolver.fields.ts
src/domain/challenge/challenge.service.ts
src/domain/opportunity/opportunity.entity.ts

removed eager loading from opportunties on challenges

---

src/utils/config/ms-graph.config.ts

MS Graph settings were wrong.
Haven't tested it.

Updated MS Graph AAD Settings

---

src/domain/ecoverse/ecoverse.service.ts

remove created user if account creation fails

---

src/domain/user-group/user-group.service.ts

update service to also load in teh focal point when loading in group members

---

src/domain/challenge/challenge.resolver.mutations.ts
src/domain/challenge/challenge.service.ts
src/domain/context/context.entity.ts
src/domain/ecoverse/ecoverse.resolver.queries.ts
src/domain/ecoverse/ecoverse.service.ts
src/domain/organisation/organisation.service.ts
src/domain/profile/profile.service.ts
src/domain/reference/reference.service.ts
src/domain/tagset/tagset.service.ts
src/domain/user/user.service.ts

There are too many errors showing up in the perf tests, so have gone through code to verify that all async funcitons are being awaited

put awaits in that were missing for async functions

---

test/challenge/challenge-test-scenarios.md
test/challenge/challenge.request.params.ts
test/challenge/create-challenge.e2e-spec.ts
test/challenge/flows-challenge.e2e-spec.ts
test/group/group.request.params.ts
test/user/user-to-group.e2e-spec.ts
test/user/user.request.params.ts

Added "flow-chellenge" tests

---

src/app.service.ts
src/domain/ecoverse/ecoverse.service.ts
src/interfaces/aad.config.interface.ts
src/utils/authentication/aad.strategy.ts
src/utils/config/aad.config.ts
src/utils/config/ms-graph.config.ts

Server 401. Fixes #401.

---

src/domain/challenge/challenge.service.ts
src/domain/ecoverse/ecoverse.service.ts
test/challenge/flows-challenge.e2e-spec.ts

The other still fails as there is another scenario to be addressed

Enabled one of the tests regarding the issue

---

graphql-samples/mutations/create/create-group-on-opportunity
graphql-samples/mutations/update/add-user-to-opportunity
src/domain/opportunity/opportunity.entity.ts
src/domain/opportunity/opportunity.interface.ts
src/domain/opportunity/opportunity.module.ts
src/domain/opportunity/opportunity.resolver.fields.ts
src/domain/opportunity/opportunity.resolver.ts
src/domain/opportunity/opportunity.service.ts
src/domain/user-group/user-group.entity.ts
src/domain/user-group/user-group.service.ts

New mutation: addUserToOpportunity
New mutation: createGroupOnOpportunity
groups file on Opportunity
contributors field on Opportunity

added groups and contributors - community - to Opportunity

---

graphql-samples/mutations/create/create-relation
src/domain/opportunity/opportunity.entity.ts
src/domain/opportunity/opportunity.interface.ts
src/domain/opportunity/opportunity.module.ts
src/domain/opportunity/opportunity.resolver.ts
src/domain/opportunity/opportunity.service.ts
src/domain/relation/relation.dto.ts
src/domain/relation/relation.entity.ts
src/domain/relation/relation.interface.ts
src/domain/relation/relation.module.ts
src/domain/relation/relation.resolver.spec.ts
src/domain/relation/relation.resolver.ts
src/domain/relation/relation.service.ts

Relation entity and associated mutations + sample file

---

src/domain/challenge/challenge.resolver.fields.ts
src/domain/opportunity/opportunity.resolver.ts
src/domain/relation/relation.dto.ts
src/domain/relation/relation.entity.ts

also extended description field size on relation

made opportunities available without authentication

---

src/domain/context/context.entity.ts
src/domain/opportunity/opportunity.entity.ts
src/domain/opportunity/opportunity.interface.ts
src/domain/opportunity/opportunity.module.ts
src/domain/opportunity/opportunity.service.ts
src/domain/organisation/organisation.entity.ts
src/domain/organisation/organisation.interface.ts
src/domain/organisation/organisation.module.ts
src/domain/organisation/organisation.service.ts

added Profile to Organisation; 
removed Profile from Opportunity; 
added Conext to Opportunity
Note: this requires a new empty db to run against.

Updated domain model to add Context + Profile to the right entities

---

src/domain/challenge/challenge.resolver.mutations.ts
src/domain/ecoverse/ecoverse.service.ts
src/domain/user-group/user-group.entity.ts
src/domain/user-group/user-group.interface.ts
src/utils/search/search.service.ts

Particularly for ecoverse authorisation related groups

added flag to group to be able to not include those groups in search

---

graphql-samples/mutations/create/create-aspect-on-project
graphql-samples/mutations/create/create-project
src/domain/aspect/aspect.entity.ts
src/domain/opportunity/opportunity.module.ts
src/domain/opportunity/opportunity.resolver.ts
src/domain/opportunity/opportunity.service.ts
src/domain/project/project.dto.ts
src/domain/project/project.entity.ts
src/domain/project/project.interface.ts
src/domain/project/project.module.ts
src/domain/project/project.resolver.ts
src/domain/project/project.service.ts

query for getting a single project by ID; 
aspects added to a project
sample files for the mutations

added mutations around creating / updating / removing projects; 

---

manifests/25-server-deployment.yaml

Update the manifest to have the correct config vars

Update the config vars in the manifest

---

graphql-samples/mutations/create/create-organisation
graphql-samples/mutations/create/create-user
src/domain/challenge/challenge.resolver.mutations.ts
src/domain/ecoverse/ecoverse.service.ts
src/domain/organisation/organisation.dto.ts
src/domain/organisation/organisation.entity.ts
src/domain/organisation/organisation.interface.ts
src/domain/organisation/organisation.service.ts
src/domain/profile/profile.service.ts
src/domain/tagset/tagset.service.ts
src/domain/user-group/user-group.service.ts
src/domain/user/user.entity.ts
src/domain/user/user.interface.ts
src/domain/user/user.service.ts
src/utils/bootstrap/bootstrap.service.ts
src/utils/data-management/data-management.service.ts

fixed bug with org creation; 
misc graphql samples tidied up; 
centralised creation of users, 
user groups, profiles into respective services
bootstrap added missing await
...

Removed tagset from profile ++

---

src/utils/bootstrap/bootstrap.service.ts

added logging of all variables on bootstrap

---

src/utils/authentication/aad.strategy.ts
src/utils/logging/logging.contexts.ts

OBO flow tracing.
Requires QA review.

Added OBO flow tracing. Closes #472.

---

src/utils/bootstrap/bootstrap.service.ts

config logging is now recursive

---

graphql-samples/queries/search/simple-search-tagsets
src/utils/search/search.service.ts

Server 437. Closes #437 and #434

---

src/domain/ecoverse/ecoverse.service.ts
src/utils/account/account.service.ts
src/utils/ms-graph/ms-graph.service.ts

Remove user accounts. Closes #484.

---

test/auth/ct anonymous - queries-mutations - access level.postman_collection.json

Added "anonymous user" tests

---

src/domain/challenge/challenge.service.ts

fixed bug whereby updating of context on a challenge was sending in the wrong entity

---

package.json
src/domain/opportunity/opportunity.resolver.ts
src/domain/opportunity/opportunity.service.ts
src/domain/project/project.resolver.ts
src/domain/project/project.service.ts

added projects, opportunities queries; fixed check for challenge name duplicates

---

package.json
src/domain/opportunity/opportunity.entity.ts
src/domain/opportunity/opportunity.resolver.fields.ts
src/domain/opportunity/opportunity.resolver.ts
src/domain/opportunity/opportunity.service.ts

Updated version
Big performance jump

Opportunity to use lazy loading for: actorGroups, relations, aspects ++

---

src/domain/ecoverse/ecoverse.service.ts
src/utils/bootstrap/bootstrap.service.ts

updated the host organisation creation so that it always exists in an initialised state

---

src/domain/opportunity/opportunity.resolver.fields.ts
src/domain/organisation/organisation.resolver.fields.ts

Fix #527. Closes #527 and #517.

---

src/utils/config/authorisation-bootstrap.json
test/challenge/challenge-test-scenarios.md
test/challenge/challenge.request.params.ts
test/challenge/create-challenge.e2e-spec.ts
test/challenge/flows-challenge.e2e-spec.ts
test/challenge/other-entities-to-challenge.e2e-spec.ts
test/group/group.request.params.ts
test/opportunity/opportunity.request.params.ts

Added Challenge tests

---

src/domain/user-group/user-group-parent.dto.ts
src/domain/user-group/user-group.module.ts
src/domain/user-group/user-group.resolver.fields.ts
src/domain/user-group/user-group.service.ts

Primarily for search results display

added user group field to obtain the parent entity

---

src/utils/error-handling/enums/cherrytwist.error.status.ts

Fixed 'undefined' enum

---

src/domain/challenge/challenge.service.ts
src/domain/opportunity/opportunity.service.ts
src/domain/profile/profile.service.ts
src/utils/bootstrap/bootstrap.service.ts
src/utils/search/search.service.ts

Fixed loops. Fixes #565.

---

src/domain/context/context.service.ts
src/domain/opportunity/opportunity.dto.ts
src/domain/opportunity/opportunity.service.ts
src/domain/reference/reference.service.ts
test/opportunity/opportunity.e2e-spec.ts
test/opportunity/opportunity.request.params.ts

Extended updateOpportunity. Closes #562.

---

src/domain/actor-group/actor-group.resolver.ts
src/domain/actor/actor.resolver.ts
src/domain/aspect/aspect.resolver.ts
src/domain/challenge/challenge.resolver.mutations.ts
src/domain/opportunity/opportunity.resolver.ts
src/domain/project/project.resolver.ts
src/utils/config/authorisation-bootstrap.json
src/utils/data-management/test-data.service.ts
test/auth/community-admin-user.e2e-spec.ts
test/auth/ecoverse-admin-user.e2e-spec.ts
test/auth/global-admin-user.e2e-spec.ts
test/utils/app.singleton.ts
test/utils/remove-mutations.ts
test/utils/update-mutations.ts

The bug is resolved.
Ecoverse admin user role tests were added as part of this issue

Server 605

---

src/domain/ecoverse/ecoverse.resolver.mutations.ts
src/domain/organisation/organisation.resolver.mutations.ts
src/utils/data-management/test-data.service.ts
test/actor-groups/actor-groups.e2e-spec.ts
test/auth/community-admin-user.e2e-spec.ts
test/auth/ecoverse-admin-user.e2e-spec.ts
test/auth/global-admin-user.e2e-spec.ts
test/challenge/create-challenge.e2e-spec.ts
test/challenge/flows-challenge.e2e-spec.ts
test/opportunity/opportunity.e2e-spec.ts
test/utils/remove-mutations.ts
test/utils/update-mutations.ts

Fixes in admin-community test and organisation resolver;
Enabe actorGroups tests;

Opportunity and challenge textID tests;

---

test/actor-groups/actor-groups.request.params.ts
test/actor/actor.e2e-spec.ts
test/actor/actor.request.params.ts

Added Actor entity CRUD api tests.

added actor CRUD tests

---

.bettercodehub.yml

Draft BCH config

---

test/functional/e2e/user-management/create-user.e2e-spec.ts
test/functional/e2e/user-management/remove-user.e2e-spec.ts
test/functional/e2e/user-management/update-user.e2e-spec.ts
test/functional/e2e/user-management/user-to-group.e2e-spec.ts
test/functional/e2e/user-management/user.request.params.ts

Stabilized user-management tests, by setting all required fields to have unique values per test/step.

Set each required user filed to be unique

---

package-lock.json
package.json
src/main.ts

Currently all middlewares are enabled and using default settings.

Added helmet security package

---

package-lock.json
package.json
src/utils/authentication/aad.obo.strategy.ts
src/utils/authentication/aad.ropc.strategy.ts

Auth logic from Tokenator

---

test/functional/integration/challenge/challenge.request.params.ts
test/functional/integration/challenge/create-challenge.it-spec.ts
test/functional/integration/challenge/query-challenge-data.it-spec.ts
test/functional/integration/context/context.request.params.ts
test/functional/integration/opportunity/opportunity.request.params.ts
test/functional/integration/organisation/organisation.request.params.ts

Extended challenge service test suites

Added challenges integration tests

---

src/domain/ecoverse/ecoverse.resolver.queries.ts
src/domain/user-group/user-group.service.ts

fixed missing async; profile updating is working - issue is members not being returned properly

---

graphql-samples/mutations/remove/remove-user-group
graphql-samples/mutations/update/update-user-group
src/domain/user-group/user-group.dto.ts
src/domain/user-group/user-group.resolver.ts
src/domain/user-group/user-group.service.ts

new mutations to remove and update groups with logic to protect restricted groups

---

test/functional/e2e/user-management/profile.e2e-spec.ts
test/functional/e2e/user-management/user.request.params.ts

added profileUpdate and query it test

---

test/functional/integration/challenge/challenge.request.params.ts
test/functional/integration/challenge/query-challenge-data.it-spec.ts
test/functional/integration/context/context.it-spec.ts
test/functional/integration/context/context.request.params.ts
test/functional/integration/references/references.request.params.ts

Added context service tests

---

src/domain/user/user.resolver.ts

Throw AuthenticationException when 'me' query is called with turned off authentication

Throw AuthenticationException when 'me' query is called

---

src/domain/challenge/challenge.service.ts
src/domain/ecoverse/ecoverse.resolver.queries.ts
src/utils/data-management/test-data.service.ts

update of how challenge instances are retrieved with populated data

---

README.md

Updated "Testing" documentation.

Updated 'testing' part of .readme

---

src/app.module.ts

Remove schema sorting because of bug: nestjs/graphql#1107

Remove schema sorting

---

test/functional/integration/group/group.request.params.ts
test/functional/integration/search/search.it-spec.ts
test/functional/integration/search/search.request.params.ts

Added earch api e2e tests

---

src/domain/user/memberof.composite.ts
src/domain/user/user.service.ts

extended memberof to include opportunities

---

src/domain/user/user.resolver.ts
src/domain/user/user.service.ts

Implement `updateMyProfile` method

---

test/functional/integration/group/group.request.params.ts
test/functional/integration/group/groups.it-spec.ts

Extended groups e2e api test suite

Extended groups e2e api test suite

---

src/domain/user-group/user-group.service.ts
test/functional/integration/group/groups.it-spec.ts

added logic to block renaming to a restricted group name

---

src/domain/user-group/user-group.service.ts
test/functional/integration/group/groups.it-spec.ts

Note: tests still need to be updated

updated behavior so that creating a group on an entity with a group with that name returns an error

---

.eslintrc.js
.lintstagedrc.json
package-lock.json
package.json

Еnable pre commit hooks

---

src/templates/ux-template.json
src/utils/config/template/user.template.entity.ts
src/utils/config/template/user.template.interface.ts

Tagset Template extended

---

test/functional/integration/actor-groups/actor-groups.it-spec.ts
test/functional/integration/actor-groups/actor-groups.request.params.ts
test/functional/integration/actor/actor.it-spec.ts
test/functional/integration/actor/actor.request.params.ts
test/functional/integration/aspect/aspect-on-opportunity.it-spec.ts
test/functional/integration/aspect/aspect-on-project.it-spec.ts
test/functional/integration/challenge/challenge.request.params.ts
test/functional/integration/challenge/create-challenge.it-spec.ts
test/functional/integration/challenge/query-challenge-data.it-spec.ts
test/functional/integration/context/context.it-spec.ts
test/functional/integration/opportunity/opportunity.it-spec.ts
test/functional/integration/relations/relations.it-spec.ts
test/functional/integration/relations/relations.request.params.ts

Removed duplicated code.
Added usage of service generated entities

Tests clean up

---

src/domain/user/user.service.ts

refactored memberOf to make cleaner, shorter

---

src/templates/ux-template.json
src/utils/config/template/application.template.entity.ts
src/utils/config/template/challenge.template.entity.ts
src/utils/config/template/ecoverse.template.entity.ts
src/utils/config/template/opportunity.template.entity.ts
src/utils/config/template/question.template.entity.ts
src/utils/config/template/template.entity.ts
src/utils/config/template/user.template.entity.ts

Add application to UX-Template

---

src/domain/user/user.service.ts

Preserve the ID when item is removed because the typeorm sets the ID to `undefined` after deletion.

Preserve ID when removing user

---

src/domain/user/user.module.ts
src/domain/user/user.resolver.mutations.ts
src/domain/user/user.service.ts
src/utils/auth/auth.module.ts
src/utils/auth/auth.service.ts
src/utils/decorators/user.decorator.ts

Unified createUser and createUserForMe

User creation refactoring

---

src/domain/user/user.resolver.mutations.ts

removed self-management from removeUser as that would not work there

---

src/services/configuration/config/authentication/providers/authentication.provider.config.entity.ts

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/cherrytwist/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/cherrytwist/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
https://github.com/cherrytwist/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

Return union type
